version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
#        MYSQL_USER: ${DB_USER}
#        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql

  frontend:
    build: ./client
    container_name: client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - backend

volumes:
  db_data: