version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - backend/.env.example
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: inventory_db
    depends_on:
      - mysql

  frontend:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: